### ISSUE TITLE
ESP32 V2 

### ISSUE THREAD

**Issue by dhalbert** [adafruit/PrettyPins#27]
The ESP32 V2 PrettyPins diagram now has 7 and 8 in the correct order, but the secondary labels are still from the old pin assignments:

![image](https://user-images.githubusercontent.com/2847802/177056761-e3f9a11e-a4af-46f5-83ba-8bc7858a01e5.png)

Current diagram in Learn Guide:
![image](https://user-images.githubusercontent.com/2847802/177056782-cab67ca7-22ea-48aa-ae8c-540e661c03ce.png)

**Comment by evaherrada** [comment]
Will take care of this today

**Comment by evaherrada** [comment]
Fixed.
https://github.com/adafruit/Adafruit-ESP32-S3-TFT-Feather-PCB
https://learn.adafruit.com/adafruit-esp32-feather-v2/pinouts
https://learn.adafruit.com/adafruit-esp32-feather-v2/downloads
